ChangeLog
src/nettle-aes/nettle-aes.c
src/nettle-sha256/nettle-sha256.c
support/beebsc.c
support/beebsc.h

Assert is not appropriate for benchmark code, and pulls in large
amounts of library function code. This patches provides a
simplified macro to replace it in two benchmarks.
This is the fix to GitHub Issue 10, see
https://github.com/embench/embench-iot/issues/10
ChangeLog:
* src/nettle-aes/nettle-aes.c (_aes_set_key, aes_set_encrypt_key)
(aes_encrypt, aes_decrypt): Replace assert with assert_beebs
throughout.
* src/nettle-sha256/nettle-sha256.c (nettle_hash_digest_func)
(sha256_write_digest): Likewise.
* support/beebsc.c: Trivial layout space adjustment.
* support/beebsc.h (assert_beebs): Macro added.

Remove calls to library assert.

---

build_all.py

In the current implementation of build_all.py, UnboundLocalError exception is raised when the timeout is reached. The following output shows the error log.
```
Traceback (most recent call last):
File "build_all.py", line 714, in <module>
sys.exit(main())
File "build_all.py", line 697, in main
res = compile_benchmark(bench)
File "build_all.py", line 505, in compile_benchmark
succeeded &= compile_file(f_root, abs_src_b, abs_bd_b)
File "build_all.py", line 477, in compile_file
log.debug(res.stdout.decode('utf-8'))
UnboundLocalError: local variable 'res' referenced before assignment
```
This pull-request fixes this issue.
ChangeLog:
* build_all.py (compile_file): assign None to res before reference.

Fix the error in the exception handling

---

src/nbody/nbody.c

This fixes issue #16
(https://github.com/embench/embench-iot/issues/16) raised by
@kohnakagawa.
Files changed:
* src/nbody/nbody.c (benchmark_body): Ensure result of
bodies_energy is used so the function is not optimized away and
check the correct value is obtained.
(verify_benchmark): Check that the benchmark got the correct total
energy value as well as setting up the solar_bodies array correcly.

Ensure nbodies benchmark uses its main function.

---

src/nbody/nbody.c

This fixes the bugs in pull request #23.
File changes:
* src/nbody/nbody.c (benchmark_body): Change the way of tot_e calculation so that the tot_e value does not depend on rpt value.
(verify_benchmark): Ensure function returns 1 when the benchmark succeeds.

Fixes the bugs in pull request #23

---

benchmark_size.py
benchmark_speed.py
build_all.py
pylib/embench_core.py

This fixes issue #20
(https://github.com/embench/embench-iot/issues/20) raised by
@quxianmiao
Files changed:
* benchmark_size.py: import check_python_version from embench_core
and use it to validate at least Python 3.6 is being used.
* benchmark_speed.py: Likewise.
* build_all.py: Likewise.
* pylib/embench_core.py (check_python_version): Created.

Ensure we use at least Python 3.6.

---

src/aha-mont64/mont64.c

aha-mont64 contains an open coded 64 x 64 -> 128 bit multiplication.
This is very sub optimal on 64 bit architectures where we could do
it in 2 instructions.
Fix this by using __int128 if available.
ChangeLog:
* src/aha-mont64/mont64.c (mulul64): Use __int128 if defined

Use __int128 for 64 x 64 -> 128 bit multiplication if available

---

README.md
doc/Makefile
doc/README.md

This clarifies the situation in the main documentation.
Files changed:
* README.md: Add Trademark designator to first use in title and
running text.
* doc/Makefile: Ignore HTML character escapes when spell checking.
* doc/README.md: Add Trademark designator to first use in title
and running text.

Note that Embench is a trademark

---

doc/README.md

Nothing groundbreaking here. I noticed that there were some small sections in `doc/README.md` that were either redundant or misleading. 
~Lyell

Correcting a couple mistakes in README.md

---

benchmark_speed.py

The relative performance calculation was inverted. I believe my colleague @GregAC had already reported this issue by email, but I independently ran into it, so for convenience I'm providing a pull request to fix it.

Fix relative performance calculation

---

benchmark_speed.py
build_all.py
doc/README.md

When compiling Embench with a debug build of clang I ran into compilation timeouts. When running the benchmark programs with a slow simulator I also ran into benchmark timeouts. These timeout values were hard-coded in the python scripts.
This patch adds options for making the timeouts configurable. As part of the implementation, the patch fixes a bug where the `populate_user_*` functions were discarding the `conf` dictionary value passed as an argument. The documentation is updated accordingly.

Add timeout options

---

doc/README.md

A quick note _in the documentation_ to make dependencies explicit.
The version of python must be >= 3.6, I've had to browse the commits to find this info.
Plus,
The check implemented in the [pull request #25](https://github.com/embench/embench-iot/pull/25) does not work : as the scripts do not compile ("SyntaxError: invalid syntax" with python 3.4 in my case), the call to check_python_version(3, 6) has no chance to run.
Best regards,
Jean-Francois

Prerequisites

---

config/native/arch.cfg
config/native/boards/default/board.cfg
config/native/boards/default/boardsupport.c
config/native/boards/default/boardsupport.h
config/native/chips/default
config/native/chips/size-test-gcc/chip.cfg
config/native/chips/size-test-gcc/chipsupport.c
config/native/chips/size-test-gcc/chipsupport.h
config/native/chips/speed-test-gcc/chip.cfg
config/native/chips/speed-test-gcc/chipsupport.c
config/native/chips/speed-test-gcc/chipsupport.h
pylib/run_native.py
support/dummy-libc.c

Add default arch/chip/board.
Default to building/running natively on the host machine when no
target arguments are passed to
build_all.py, benchmark_speed.py & bencmark_size.py.
Files changed:
benchmark_speed.py: Use 'run_default' as default for target_module.
build_all.py: Use 'default' as default for arch.
config/default/arch.cfg: New file.
support/dummy-libc.c: Add functions needed by x86_64/GCC-9.
config/default/boards/default/board.cfg: New file.
config/default/boards/default/boardsupport.c: New file.
config/default/boards/default/boardsupport.h: New file.
config/default/chips/default: New symlink 'speed-test-gcc'.
config/default/chips/size-test-gcc/chip.cfg: New file.
config/default/chips/size-test-gcc/chipsupport.c: New file.
config/default/chips/size-test-gcc/chipsupport.h: New …

Add default arch/chip/board

---

pylib/run_stm32f4-discovery.py

Files changed:
* pylib/run_stm32f4-discovery.py (cpu_mhz): Global defined,
defaults to 1.
(def get_target_args): Set CPU MHz from args.
(def decode_results): Use CPU MHz to convert cycles to milliseconds.

Make sure STM Discovery Board converts cycles -> milliseconds.

---

doc/README.md
doc/custom.wordlist

This incorporates the changes from a full review of the
documentation.
Files changed:
* doc/README.md: Bump version to 0.5, and clarify legacy
versioning of the documentation; correct details of building and
running the benchmarks; more detail on what must be recorded for
an Embench run; describe Embench per MHz scores; update baseline
to be Cortex M4;
* doc/custom.wordlist: Add words to support changes to documentation.

Documentation finalized for release 0.5.

---

pylib/run_stm32f4-discovery.py

speed benchmark.
The absence of a --cpu-mhz value on the command line
when running the speed benchmark caused cpu-mhz to
default to a None value.
Files changed:
* pylib/run_stm32f4-discovery.py: default value of
--cpu-mhz = 1.

Add default value to --cpu-mhz attribute of stm32f4-discovery

---

config/arm/boards/stm32f4-discovery/boardsupport.c

The dummy instructions in the support functions for the board interfere
with the setting of the cycle counter when compiling with Clang.
Since the support functions now manage the cycle counter there's no
need for dummy instructions.
Files changed:
* config/arm/boards/stm32f4-discovery/boardsupport.c:
removed dummy asm instructions.

Remove dummy asm instructions for stm32f4-discovery

---

build_all.py

The split separator cause the parsing of the arguments to fail if multiple
spaces are used. Without specifying the separator the parsing is more robust.
Files changed:
* build_all.py: removed split space separator.

Remove split space separator (#51)

---

doc/README.md

Files changed:
* doc/README.md: Fix typos in argument names.

Fix a number of typos in documentation where _ should be -

---

build_all.py

If a user has enabled debug output from their compiler or
linker then it is helpful for it to not be swallowed by
the build system.
Alternatively perhaps this could depend on the presence of the `--verbose` flag?

Always log output from the compiler and linker

---

build_all.py

This fixes Issue 69 on GitHub.
Files changed:
* build_all.py (def compile_file): Only attempt to log if we did
some compilation.
Signed-off-by: Jeremy Bennett <jeremy.bennett@embecosm.com>

Fix problems with rebuilding.

---

doc/README.md

This fixes Issue 70 on GitHub.
Files changed:
* doc/README.md (Prequisites): Note that pyelftools is a prerequisite.
Signed-off-by: Jeremy Bennett <jeremy.bennett@embecosm.com>

Add missing prerequisite.

---

config/riscv32/chips/generic/chipsupport.h
src/wikisort/libwikisort.c

These commits remove the uses of the gcc specific typeof extension and eliminate a pedantic ISO C compliance error with a dummy typedef.

Remove gcc specific typeof and fix an ISO C compliance error (#72)

---

README.md
doc/README.md

We lost the beebs.eu domain. Update with the replacement domain.
Files changed:
* README.md: Migrate beebs.eu -> beebs.mageec.org.
* doc/README.md: Likewise.
Signed-off-by: Jeremy Bennett <jeremy.bennett@embecosm.com>

Update links to BEEBS

---

build_all.py

Move the **res** variable log printing inside the **try** block.
clearly the case here is that the _try_ block has failed at _line 666_ and the program is bounced to the exception at _line 677_.
therefore when getting to _line 686_, the **res** variable has not been initialized yet.
hence no one is likely to use the **res** variable outside the try block, the debug log lines are moved inside the **try** block.

Fix of issue #103

---

doc/README.md

This changes start_benchmark and end_benchmark to start_trigger and end_trigger in doc/README.md. This file has not had the toc regenerated, nor been run through the spelling checker.
There are two commits in here. The second corrects the first. The first had deleted some important text from the file when I attempted to rebuild the toc.

Fix to issue #113 pt 1

---

src/huffbench/libhuffbench.c
src/sglib-combined/combined.c
support/beebsc.c

Fix issue #116.
Until now, `malloc_beebs` and `realloc_beebs` returned non-aligned pointer and this behaviour could result in a performance penalty in some tests that use the heap, especially when executed on some architectures.
This commit makes `malloc_beebs` return pointers aligned to multiples of `sizeof(void *)`, and also updates `realloc_beebs` to make use of that.
To avoid breaking changes, the padding is added to heap_requested.
This commit also makes the static array used as a heap in sglib-combined and huffbench aligned. This is obtained through the `__attribute__((aligned))` directive as it seems to be well supported across compilers.

Make custom malloc & realloc return aligned pointers

---

baseline-data/size.json
baseline-data/speed.json
src/primecount/primecount.c

The test primecount searches and counts the prime numbers up to a given limit.
This version of the test is a reduction of the test proposed by Bruce Hoult.
The limit has been reduced in order to fit the execution time on a Cortex M4
working at 16 MHz into 4 seconds.
Files changed:
* src/primecount/primecount.c: Created.
* baseline-data/size.json: Added the result for primecount.
* baseline-data/speed.json: Likewise.
Thanks to Bruce Hoult <bruce@hoult.org> for providing the test.

Add primecount test.

---

src/md5sum/md5.c

Although malloc_beebs() was used for malloc(), but calloc_beebs() was not used for calloc().
As result calloc() failed.
Use calloc_beebs() for calloc() and increase the heap size for it.
---
The result value was the sum of four uint32_t values.
The result changes between 32bit and 64bit CPUs.
Using XOR (Exclusive OR) fixes the issue.

md5sum: make calloc() use calloc_beebs() and use XOR for result value

---

pylib/run_native.py

When run_native like below, I get a error and find md5sum's RET check error. I found the regexp pattern for stdout RET line has a bug when stdout has multiline and RET line not the first line ( or maby md5sum program should not produce output).
```
./benchmark_speed.py --target-module run_native
Benchmark           Speed
---------           -----
aha-mont64         4004000.00
crc32              4010000.00
cubic              3931000.00
edn                4010000.00
huffbench          4120000.00
matmult-int        3985000.00
md5sum                   
minver             3998000.00
nbody              2808000.00
nettle-aes         4026000.00
nettle-sha256      3997000.00
nsichneu           4001000.00
picojpeg           4030000.00
primecount         3834000.00
qrduino            4253000.00 …
```

fix md5sum RET parse error

---

benchmark_size.py
benchmark_speed.py
pylib/embench_core.py

Sister push to jsonfix, this fixes the same issue in the Embench-1.0-branch which is stable. 
Contains the fixes for the JSON file output. The extra { and } in the benchmark_speed.py and benchmark_size.py let the json output be correctly inputted by computers. For JSON outputs, we do not want to print All benchmarks sized successfully, as this ruins the json file. Failed runs will not have the trailing }.
On the Embench_core.py file, the .format python function looks for { and } in the string. Because we need a }, the .format function gets confused and wonders why there isn't a { to give the bounds of what to replace. Currently, this throws a pretty nasty error (at least on my machine). We can fix this by using string concatenation.
log.info(' }' + '{oc}'.format(oc=opt_comma))

jsonfix for embench 1.0

---

config/riscv32/boards/rv32wallyverilog/link.ld

We found a bug causing qrduino to stall in Embench 1.0 on Wally. Weird we didn't see this earlier, but here's the simple fix.

Wally Embench 1.0 Linker File Bug

---

src/md5sum/md5.c

The md5sum benchmark included `printf` calls which were not guarded by any flag, meaning that the benchmark relied on stdout and requires any platform to support linking against a functional libc implementation.
With the added `#DEBUG` guard, none of the benchmarks perform I/O.

Guard md5sum printf by DEBUG
